# Generated by Django 2.2.13 on 2020-11-02 22:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wesgarlock.base.models._base


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wesgarlockbase', '0002_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField(default='')),
                ('meta_description', models.CharField(blank=True, max_length=120, null=True)),
                ('og_description', models.CharField(blank=True, max_length=300, null=True)),
                ('about_me', wagtail.core.fields.RichTextField()),
                ('about_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('hero_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('og_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('primary_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_homepage_link', to='wagtailcore.Page')),
                ('secondary_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_homepage_link', to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'home_page',
                'verbose_name_plural': 'home_pages',
            },
            bases=(wesgarlock.base.models._base.BasePageMixin, 'wagtailcore.page'),
        ),
    ]
