# Generated by Django 2.2.13 on 2020-11-15 01:12
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesgarlockbase', '0003_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=secrets.token_hex(8), editable=False, max_length=16),
            preserve_default=False,
        ),
    ]
