# Generated by Django 3.1 on 2020-11-27 20:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wesgarlock.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wesgarlockbase', '0004_addsalt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='SiteColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js_name', models.CharField(max_length=255)),
                ('is_list', models.BooleanField(default=False)),
                ('site', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_colors', to='wesgarlockbase.sitecontent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('none', 'None'), ('main', 'Main'), ('light', 'Light'), ('dark', 'Dark'), ('darkBlack', 'Dark Black'), ('black', 'Black')], default='main', max_length=255)),
                ('hex_color', models.CharField(default='#000000', max_length=7, validators=[wesgarlock.base.validators.hex_validate])),
                ('site_color', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colors', to='wesgarlockbase.sitecolor')),
            ],
            options={
                'unique_together': {('type', 'site_color')},
            },
        ),
    ]
