# Generated by Django 3.1.3 on 2020-11-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesgarlockbase', '0005_sitecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='site_email',
            field=models.EmailField(default='Test@test.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='site_phone',
            field=models.CharField(default=1111111111, max_length=16),
            preserve_default=False,
        ),
    ]
